server:
  port: 8763

# eureka服务端
eureka:
  client:
    register-with-eureka: false  # 是否要注册到eureka中，它自己就是eureka
    fetch-registry: false # 是否要从eureka注册中心获取信息
    serviceUrl:
      # 1、eureka 单机部署
#      defaultZone: http://localhost:${server.port}/eureka/
      # 2、集群部署eureka，高可用
      defaultZone: http://lq:lq@eureka8761:8761/eureka,http://lq:lq@eureka8762:8762/eureka
  instance: #eureka实例定义
    hostname: eureka8763 # 定义 Eureka 实例所在的主机名称
    prefer-ip-address: true #实例名称显示ip
  server:
    enable-self-preservation: false     #设置为false表示关闭保护模式
    eviction-interval-timer-in-ms: 45000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）

# Eureka service 增肌安全机制，可以外网访问，更加安全，需要添加security jar包
spring:
  security:
    user:
      name: lq
      password: lq
